name: Deploy WebAPP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configuração do Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Passo 3: Login no Docker Hub ou GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 4: Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t escalasapp:latest .

      # Passo 5: Enviar a imagem Docker para o Docker Hub
      - name: Push Docker image
        run: |
          docker tag escalasapp:latest ${{ secrets.DOCKER_USERNAME }}/escalasapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/escalasapp:latest

      # Passo 6: Fazer o deploy para a EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Parar e remover container anterior
            docker stop escalasapp || true
            docker rm escalasapp || true

            # Puxar a última versão da imagem
            docker pull ${{ secrets.DOCKER_USERNAME }}/escalasapp:latest

            # Rodar o container com a imagem mais recente
            sudo docker run -d --name escalasapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/escalasapp:latest
